spring:
  application:
    name:
      member-service

  profiles: # DB 패스워드
    include: password

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  messages:
    basename: errors

server:
  port: 0

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}


