spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member-service/**
          filters:
            - RewritePath=/member-service/(?<segment>.*), /$\{segment}

        - id: platform-service
          uri: lb://PLATFORM-SERVICE
          predicates:
            - Path=/platform-service/**
          filters:
            - RewritePath=/platform-service/(?<segment>.*), /$\{segment}


        - id: review-service
          uri: lb://REVIEW-SERVICE
          predicates:
            - Path=/review-service/**
          filters:
            - RewritePath=/review-service/(?<segment>.*), /$\{segment}

server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
