spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/api/login, /api/sign-up, /api/logout

        - id: platform-service
          uri: lb://PLATFORM-SERVICE
          predicates:
            - Path=/api/platform, /api/platforms, /api/platform/**

        - id: review-service
          uri: lb://REVIEW-SERVICE
          predicates:
            - Path=/api/review

server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
