spring:
    application:
        name: eureka

server:
    port: 8761

eureka:
  client:
      fetch-registry: false
      register-with-eureka: false

  instance:
      lease-expiration-duration-in-seconds: 30
