spring:
  application:
    name: validate-library
  data:
    redis:
      host: localhost
      port: 6379
eureka:
  client:
    register-with-eureka: false

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        sliding-window-type: count_based
        wait-duration-in-open-state:
          seconds: 1
        failure-rate-threshold: 50
  timelimiter:
    configs:
      default:
        timeout-duration:
          seconds: 4


